#!/usr/bin/env python3
#
# pylint: disable=invalid-name

"""
Launch the Ethereum Gas Price Oracle.

AUTHOR:
  ethgasstation
  Marcus R. Brown <contact@marcusrbrown.com>

LICENSE:
  MIT License
  https://opensource.org/licenses/MIT
"""

from gasstation_express_oracle import server

server.master_control()
